### ISSUE TITLE
app id range

### ISSUE THREAD

**Issue by john30** [OpenKNX/OpenKNX#1]
hey guys, I'd like to apply for being listed with app id range 0xaeb0 - 0aebf [in the wiki](https://github.com/OpenKNX/OpenKNX/wiki/Information-about-KnxProd#applicationnumber) for use with my [ebusd](https://github.com/john30/ebusd) KNX integration ("aeb" because that fits best to other IDs I'm already using, e.g. a MAC address prefix ae:b0:53 in https://adapter.ebusd.eu/

**Comment by john30** [comment]
how was this completed exactly?

**Comment by Ing-Dom** [comment]
The OpenKNX Application IDs are reserved for OpenKNX Applications, maintained by the OpenKNX Team.
Your ebusd integrations is not an OpenKNX Application, therefore it must not use an OpenKNX ID.
