### ISSUE TITLE
OpenETS

### ISSUE THREAD

**Issue by tobylorenz** [OpenKNX/OpenKNX#5]
Hi,

great that there is now a centralized Open Source collaboration on KNX.

I just wanted to mention that I'm working on an OpenETS implementation (Qt-based).
What is working:
* Support for ETS schemas: v1.0, v1.1, v1.2, v1.3, v1.4, v2.0. One selected during compile time.
* Visualization of KNX project, manufacturer data, master data.
* Most application layer functionality implemented directly, so without most Application Interaction Layer on top yet.
What is to be done:
* Support multiple ETS schemas in parallel.
* Full support of all ETS functionality resp. Application Interaction Layer functionality.
* ETS signing support to allow import of modified files in original ETS.

The link is here: https://bitbucket.org/tobylorenz/openets/src/master/

OpenETS itself is based upon an own KNX stack, which I wrote in C++ using libasio.
It is based on the latest published KNX specification v2.1 plus some extensions, application notes (KNX secure), and collected know how.
The implementation provides backward traceability to the specification.
The tests are all implemented, and the implementation passes the tests mostly. Some implementation is not finished yet.
The tests mostly simulate a network consisting of two or more KNX devices, hence, the stack can also be used for rest bus simulation or virtual KNX devices, or for interoperability tests.
I fear that there is a major rework needed, when KNX v3 spec comes out, as the whole source code structure currently follows the KNX v2.1 chapters.

The link is here: https://bitbucket.org/tobylorenz/knx/src/master/

Bye
Tobias

**Comment by gillhofer** [comment]
Wow, great work!

Is there a way one could help?

**Comment by Ing-Dom** [comment]
Hi Tobias,

wenn du mit uns in Kontakt treten möchtest ist unser Unterforum im KNX-User-Forum der richtige Ort:

https://knx-user-forum.de/forum/projektforen/openknx

**Comment by nerdoc** [comment]
Cool, thanks.
Small hint (normally I would create a fork and PR as I do that in GitHub/Gitlab - but I can't fork it - no permissions for a Workspace, blah - don't know - I need to get used to Bitbucked I think.

"libquazip1-qz6-dev" should mean "libquazip1-qt6-dev" - and maybe put a sudo before the line, for convenience.

**Comment by tobylorenz** [comment]
I'll check the repository permissions. Doesn't make sense that forking
is not allowed, I agree.

Thanks for the correction. I've changed it and upload it with the next
commit.

Bye Tobias

Am 13.01.25 um 11:21 schrieb Christian González:
