### ISSUE TITLE
what about suppot of STKNX

### ISSUE THREAD

**Issue by leoujz** [OpenKNX/OpenKNX#6]
OpenKNX is a great work.

currently I found the TPUART2(OnSemi NCN51xx) supported by [thelsing knx stack](https://github.com/thelsing/knx), is there any way to support [STKNX](https://www.st.com/en/interfaces-and-transceivers/stknx.html) which is much cheaper?

**Comment by Ing-Dom** [comment]
STKNX is like the NCN5110 a "bitstream" access to the bus. It only handles the physical layer, while TPUart, NCN512x / 3x and the elmos chip handle also most of the data link layer.
Therefor, this would be a lot more timing critical and not a easy task.

As a side effect, the discrete selfbus bus connection could also be used.

If you are willing to do this, feel free to PR a solution to https://github.com/OpenKNX/knx.
